import * as ADMIN from "../pages/ADMIN/index";
import { DashboardIcon, UserPlusIcon } from "../assets/resources/icon/Icons";
import {
  CarOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  HomeOutlined,
  TeamOutlined,
  UserAddOutlined,
  UsergroupAddOutlined,
  UserOutlined,
} from "@ant-design/icons";

export const nav = [
  {
    path: "/dashboard",
    name: "Dashboard",
    component: <div>Test</div>,
    icon: <DashboardIcon />,
    isFilter: true,
    isShow: true,
    accountType: "SUPERADMIN",
  },
  {
    path: "/dashboard",
    name: "Dashboard",
    component: <ADMIN.Dashboard />,
    icon: <DashboardIcon />,
    isFilter: true,
    isShow: true,
    accountType: "MEMBER",
  },

  // {
  //   path: "membership",
  //   name: "Membership",
  //   // component: <ADMIN.Member />,
  //   icon: <UsergroupAddOutlined />,
  //   isFilter: true,
  //   isShow: true,
  //   accountType: "MEMBER",
  //   children: [
  //     {
  //       path: "member",
  //       name: "Members",
  //       component: <ADMIN.Member />,
  //       // icon: <UserPlusIcon />,
  //       isFilter: true,
  //       isShow: true,
  //     },
  //     {
  //       path: "registration",
  //       name: "Registration",
  //       component: <ADMIN.Registration />,
  //       // icon: <UserPlusIcon />,
  //       isFilter: true,
  //       isShow: true,
  //     },
  //   ],
  // },

  {
    path: "/registration",
    name: "Registration",
    component: <ADMIN.Registration />,
    icon: <UserAddOutlined />,
    isFilter: true,
    isShow: true,
    accountType: "MEMBER",
  },
  {
    path: "member",
    name: "Members",
    component: <ADMIN.Member />,
    icon: <UserOutlined />,
    isFilter: true,
    isShow: true,
    accountType: "MEMBER",
    children: [
      {
        path: "pending",
        name: "Pending",
        component: <ADMIN.Pending />,
        icon: <ClockCircleOutlined />,
        accountType: "MEMBER",
      },
      {
        path: "accepted",
        name: "Accepted",
        component: <ADMIN.Accepted />,
        icon: <CheckCircleOutlined />,
        accountType: "MEMBER",
      },
    ],
  },
  {
    path: "/stall",
    name: "Stalls",
    component: <ADMIN.Stall />,
    icon: <HomeOutlined />,
    isFilter: true,
    isShow: true,
    accountType: "MEMBER",
  },
  {
    path: "/parking",
    name: "Parking",
    component: <ADMIN.Parking />,
    icon: <CarOutlined />,
    isFilter: true,
    isShow: true,
    accountType: "MEMBER",
  },
  {
    path: "/account",
    name: "Accounts",
    component: <ADMIN.Accounts />,
    icon: <TeamOutlined />,
    isFilter: true,
    isShow: true,
    accountType: "MEMBER",
  },
];
